### ISSUE TITLE
SBT snippet in readme points to wrong project

### ISSUE THREAD

**Issue by garantiertnicht** [Katrix-/AckCord#1]
In the readme.md you specify that the dependency can be added by adding `libraryDependencies += "net.katsstuff" %% "ackCord" % "0.2"` (with uppercase C in ack**C**ord). However, on the public maven is located at https://oss.sonatype.org/content/repositories/public/net/katsstuff/ackcord_2.12/0.2/ (with lowercase C in ack**c**ord) and the urls are case sensitive. Eigther move your project on sonatype (if that is possible) or ajust your readme.md

**Comment by Katrix-** [comment]
Well oops. Thanks for the notice. I managed to get it right for the commands apparently.
