### ISSUE TITLE
No option for mention-less commands in higher-level command registry

### ISSUE THREAD

**Issue by llamositopia** [Katrix-/AckCord#2]
In the usage of 
`client.registerCommand` in the higher-level API there is no option to create commands that do not require a mention, unlike the previous low-level API that did allow these commands to be registered.

**Comment by Katrix-** [comment]
When creating you `ClientSettings` pass in a custom `CommandSettings`. Here you can set mention-less commands. Remember to also specify all the command categories here. Does that answer your question?

**Comment by llamositopia** [comment]
Yep, I tried looking all over except where it was needed 👍
