### ISSUE TITLE
Requests should by default drop null values

### ISSUE THREAD

**Issue by llamositopia** [Katrix-/AckCord#3]
The RequestDSL in the high-level command API gets stuck attempting to call `channel.fetchMessages` or any of its variants, preventing the bot from executing further portions of the DSL, as well as any other commands.

```Scala
cmd: ParsedCmd[Int] => {
    for {
        channel <- {
            println("A")
            maybePure(cmd.msg.tGuildChannel)
        }
        messages <- {
            println("B")
            channel.fetchMessagesBefore(cmd.msg.id, limit = Some(cmd.args))
        }
        _ <- {
            println("C")
            channel.bulkDelete(messages.map(q => q.id))
        }
    } yield ()
}
```
will only print 
```
A
B
```
and immediately following the bot will not respond to future commands.

**Comment by Katrix-** [comment]
Tracked it down to having nothing to do with RequestDSL. Instead, null values in the json are being kept around currently. It's an easy fix for most cases, however, requests that have parameters where it's not clear if the Option means "put a null here" or "don't put a field here" will be a bit more difficult. For those cases, I'll look at adding a separate datatype to represent those cases.

Currently, I think I'll stick with Option for requests where all null parameters can be dropped from the json.

**Comment by Katrix-** [comment]
Turns out fetchMessages was broken too. Query parameters. Anyway, fixed now.
